version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Unit tests
          command: yarn jest --ci
          environment:
            JEST_JUNIT_OUTPUT: "coverage/junit/js-test-results.xml"
      - store_test_results:
          path: coverage/junit
      - store_artifacts:
          path: coverage/junit
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
